- .github/workflows/shellcheck.yaml
- .github/workflows/tools.yaml
- .github/workflows/workflows.yaml
- test/tools/tool1/.shed.yml
- test/tools/tool1/tool1.xml
- test/tools/tool2/.shed.yml
- test/tools/tool2/tool2.xml
- test/workflows/example3/.dockstore.yml
- test/workflows/example3/data/dataset1.txt
- test/workflows/example3/data/dataset2.txt
- test/workflows/example3/data/output.txt
- test/workflows/example3/output.json
- test/workflows/example3/tools.yml
- test/workflows/example3/tutorial-job.yml
- test/workflows/example3/tutorial-tests.yml
- test/workflows/example3/tutorial.ga
- test/workflows/example3/tutorial_output.txt
- test/workflows/example4/.dockstore.yml
- test/workflows/example4/data/dataset1.txt
- test/workflows/example4/data/dataset2.txt
- test/workflows/example4/data/output.txt
- test/workflows/example4/output.json
- test/workflows/example4/tools.yml
- test/workflows/example4/tutorial-job.yml
- test/workflows/example4/tutorial-tests.yml
- test/workflows/example4/tutorial.ga
- test/workflows/example4/tutorial_output.txt
implements three independent workflows
- seperate workflows for tools and workflows (necessary because artifacts would be mixed otherwise in the combine step)
- and one running shellcheck
I already tested this quite a bit. So I would suggest to merge this and test it in action for https://github.com/galaxyproject/planemo-ci-action/pull/3 (some shell check errors will need to be fixed. but I think I know how to do it).
> implement github actions workflows for push and pull_request

- .github/workflows/tools.yaml
- .github/workflows/workflows.yaml
- README.md
- planemo_ci_actions.sh
The first runs of the workflows failed to some extent: 
- the combine job missed the checkout that is needed to run `./` this is fixed in this PR ~.. but we won't see the effect in the PR .. but only when its merged~
- the `setup as in PR` jobs failed because the tools and workflows have been added in the same commit .. which violates some assumption of the test, i.e. which tools/workflows changed .. this does not happen normally
I was also thinking
- if we should install python in the action (only for the setup and flake8 jobs we would need to have an [additional] python setup step)
- if we should have releases for this action?
> checkout local action in all jobs and shellcheck fixes

- action.yml
This is needed if we want to deploy to a different repository.
`planemo workflow_upload` autoamtically takes this from the environment variables.
> Add github-token for workflow deployment

- planemo_ci_actions.sh
currently the chunk count depends only on the number of changed tools.
but the tool test uses all tools in the changed repos. therefore the
computed number of chunks is to low.
for the linting step we still need the changed tools (for the .shed.yml
test).
for CI (i.e. when $COMMIT_RANGE is empty) the two calls to ci_find_tools
yield identical results and we might think about saving one...
> count all tools in changed repo to get chunk count

- .github/workflows/tools.yaml
- planemo_ci_actions.sh
- test/tools/tool2/tool2.xml
to make the action detect linter errors again.
recently (https://github.com/galaxyproject/planemo-ci-action/pull/15) a pipe was introduced to redirect linter output:
`planemo shed_lint ... | tee -a lint_report.txt`
without pipefail linter errors are not detected anymore.
> add pipefail

- .github/workflows/tools.yaml
- README.md
- action.yml
- test/tools/galaxy_slots/.shed.yml
- test/tools/galaxy_slots/galaxy_slots.xml
this will enable that each Galaxy job started within planemo test can use more than the default of 1 CPU core
if I interpret the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)  correctly there should be 2 available in github hosted runners.
not sure if this is the best for workflow testing? is it possible in workflow tests to run multiple Galaxy jobs parallel? If so then we probably would like to set this in job_conf, or?
> support setting GALAXY_SLOTS

- .github/workflows/tools.yaml
- README.md
- action.yml
- planemo_ci_actions.sh
> add planemo lint error/warn level parameters

- README.md
- action.yml
- planemo_ci_actions.sh
xref https://github.com/galaxyproject/planemo/pull/1236
alternatively we could just set the env variable and drop the referenced planemo PR .. not sure what is desired
> add option to limit test run time

- planemo_ci_actions.sh
- test/workflows/example4/tutorial.ga
Given the long startup time when all tools are loaded from CVMFS this might be faster, tests against the IWC will run even if the tool is not (yet) installed on main, and non-iwc repos that don't necessarily have their tools installed on main can use this. Also drops the explicit `--tool_data_path` option, which was added for mounting in test data in the job container, but that's covered by `--docker_extra_volume` and should be faster at startup.
> Install tools from shed

- .github/workflows/workflows.yaml
- planemo_ci_actions.sh
Because we keep the same database connection Galaxy thinks repos are installed after the first workflow test, when they are not because planemo generated a new shed_tool_conf file. This fixes most of the tests in https://github.com/galaxyproject/iwc/pull/174
> Keep shed_tool_conf and shed dir in between runs

- planemo_ci_actions.sh
currently the combine step just outputs a set of "error" or "failure" strings for such tests. it would be much more useful to know immedately, i.e. without checking the html output, which tests failed.
this info should now be visible
just tested for the json output of
https://github.com/galaxyproject/tools-iuc/actions/runs/4798624079/jobs/8538223205 .. output looks like
```
...
"failure;mothur_remove_lineage;2"
"error;mothur_remove_lineage;3"
"error;mothur_remove_lineage;4"
"success;mothur_remove_otulabels;0"
...
```
Add a test? Not sure if it's worth to add an output, or possible to test stdout of an action?
> add tool_id and test_index to jq output

- planemo_ci_actions.sh
Problem was that 
```
if false | true; then
echo F;
fi
```
does not fail, despite `pipefail`...
with `false` being `jq .. WRONG_PATH` in out case.
> fix path for check mode

- planemo_ci_actions.sh
otherwise the 1st job does not profit from this
There was a recent discussion with @mvdbeek (https://github.com/galaxyproject/tools-iuc/pull/4935#issuecomment-1321759775) to do this in a loop running in the background. I thought about this: I think the problem is that the containers would be pruned also inbetween tests of the same tool / tool repo with the same requirements (and therefore the same container).
> prune docker containers (continuously)

- planemo_ci_actions.sh
Revert https://github.com/galaxyproject/planemo-ci-action/pull/37 and prune once before each `planemo test`.
When testing tools for which no container exists one is built. The continuous pruning makes this fail ([example](https://github.com/galaxyproject/tools-iuc/pull/5413)). It seems that also some `./build` directory is pruned and docker recreates it with root permissions ([see](https://github.com/galaxyproject/galaxy/blob/26031d6a401f1d57c4d3e0b5db2e86c65ab40445/lib/galaxy/tool_util/deps/mulled/mulled_build.py#L412)). Besides this it seems more than likely that a `prune` is called between subsequent tests and maybe even between building the container and using it in the test. Hence the container needs to be built frequently which often needs enormous amounts of time.... besides the …
> Revert continuous pruning of containers

- .github/workflows/tools.yaml
- planemo_ci_actions.sh
`planemo lint` breaks the loop after the first tool that fails linting. Hard to spot because most jobs contain a single tool and in the past we used `fail_level` `error` which happened seldomly for multiple tools.
> Fix lint job stopping early after first failure

- .github/workflows/tools.yaml
- planemo_ci_actions.sh
uses https://github.com/galaxyproject/planemo/pull/1462
> Create minimal markdown report if too large

- .github/workflows/tools.yaml
- README.md
- action.yml
- planemo_ci_actions.sh
- test/tools/tool1/.lint_skip
that allows to list linters to be skipped. A skip file in the repo root and in the tool dir are allowed (and joined).
TODO:
> Add handling of `.skip_lint` file(s)

- .github/workflows/tools.yaml
- test/tools/fail/.shed.yml
- test/tools/fail/galaxy_slots.xml
fixes https://github.com/galaxyproject/planemo-ci-action/issues/48
> add test for failing tool

- planemo_ci_actions.sh
somehow this was completely messed up:
```
-f, --file-system     display file system status instead of file status
%z   time of last status change, human-readable
```
should be fine now:
```
-c  --format=FORMAT   use the specified FORMAT instead of the default;
output a newline after each use of FORMAT
%s   total size, in bytes
```
> Fix stat call

- .github/workflows/tools.yaml
- .github/workflows/workflows.yaml
xref:
Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact. After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.
> Upgrade GitHub Actions to use version 4 for upload and download artifacts
